### ISSUE TITLE
[EPIC] Cluster API Operator's helm chart is a wreck

### ISSUE THREAD

**Issue by cloudymax** [cloudymax/kubevirt-community-stack#51]
This ones gonna need some work...

- [x] add missing multiple important resources
- [x] puts stuff in the right namespaces
- [x] add missing certs/issuers
- [x] add missing service accounts
- [ ] Get feature gates working for Kubevirt-Manager
- [x] Document steps for working cluster

**Comment by cloudymax** [comment]
so close to being done but holiday break is over 😢
